### General Settings ###
# The name of the item in-game
item-name: "§aEnder Bag"
# The description of the item in-game
item-description: "§bOpen your ender chest"
# Should the description be shown?
show-description: true
# Should the item have an enchanted appearance? This helps distinguish the item if not using the resource pack
appear-enchanted: false
# The base item to use as the "model" (If this is changed from `ender_eye` and you use the
# resource pack, you will need to update the pack to point to the correct item)
base-item: "ender_eye"

### Cooldown Settings ###
# Should there be a cooldown on use?
cooldown: false
# Time between usages of the item
cooldown-time: 2m
# Message shown when you attempt to use the item before it is ready
cooldown-message: "You cannot use the %n yet."

### Durability Settings ###
# Should the item have durability
durability: false
# What is the maximum durability
max-durability: 100
# Durability subtracted per use (see safe-durability)
durability-per-use: 1
# Durability will only be subtracted if an item is inserted/taken from the chest
safe-durability: false
# Should the item be completely destroyed at 0 health?
unbreakable: true;
# What item should be used for repairs at the anvil?
repair-item: "ender_chest"
# How much durability should a single repair restore?
repair-amount: 100
# The durability value where the bag will be marked as "damaged". Sets the model data as described in the readme.
# -- Only relevant to clients if they are using a custom resource pack supporting this plugins model data --
damaged-threshold: 50

### Recipe Settings ###
# Recipe for the item
recipe:
  values: [
    "DED",
    "ECE",
    "DED"
  ]
  key: [
    ["D", "diamond"],
    ["E", "ender_eye"],
    ["C", "ender_chest"]
  ]