name: EnderBag
author: Roflsausage
version: ${revision}
main: org.mries.enderbag.EnderBag
api-version: "1.13"
softdepend: ["ProtocolLib"]
permissions:
  enderbag.use:
    description: Allows you to use the ender bag
    default: true
  enderbag.command:
    description: Allows you to open the ender bag using a slash command
    default: op
  enderbag.give.self:
    description: Allows you to give yourself an ender bag
    default: op
  enderbag.give.others:
    description: Allows you to give an ender bag to other players
    default: op
commands:
  enderbag:
    description: The base command for interacting with EnderBag
    aliases: ["eb", "enderchest", "ec"]